packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/123pan-api-sdk/packages/*'
shamefullyHoist: true
allowBuilds:
  electron: true
  esbuild: true
  electron-winstaller: true
  vue-demi: true
minimumReleaseAgeExclude:
  - rolldown-plugin-dts@0.28.3
