/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FileTable: typeof import('./src/components/drive/FileTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_0286c7ae9f183c1bc0782e82f34987a2/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_0286c7ae9f183c1bc0782e82f34987a2/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UButton: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_0286c7ae9f183c1bc0782e82f34987a2/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UDropdownMenu: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_0286c7ae9f183c1bc0782e82f34987a2/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UIcon: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_0286c7ae9f183c1bc0782e82f34987a2/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_0286c7ae9f183c1bc0782e82f34987a2/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UNavigationMenu: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_0286c7ae9f183c1bc0782e82f34987a2/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UProgress: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_0286c7ae9f183c1bc0782e82f34987a2/node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    UTable: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_0286c7ae9f183c1bc0782e82f34987a2/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
  }
}
