/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DownloadManager: typeof import('./src/components/drive/DownloadManager.vue')['default']
    FileTable: typeof import('./src/components/drive/FileTable.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareView: typeof import('./src/components/drive/ShareView.vue')['default']
    TrashView: typeof import('./src/components/drive/TrashView.vue')['default']
    UAlert: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCheckbox: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UDropdownMenu: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UForm: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPopover: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    UProgress: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USeparator: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USwitch: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTable: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./../../../../node_modules/.pnpm/@nuxt+ui@4.11.0_063aac3df06fa62674f33bc199c8c8d4/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
